using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DBFirstLibrary  // must be the same namespace as for the generated models!
{
    public partial class Author  // keyword partial extends an existing class Author generated by scaffolding
    {
        [Timestamp]
        public byte[] RowVersion { get; set; }  // the property (concurrency token) is used for optimistic concurrency: https://learn.microsoft.com/en-us/ef/core/saving/concurrency?tabs=data-annotations#optimistic-concurrency

        public override string ToString()
        {
            return Name;
        }
    }
}
